### ISSUE TITLE
Key and secret change and something else...

### ISSUE THREAD

**Issue by mic-rigaud** [xbgmsharp/allocine#5]
Hello,

The API has not been running for several days. I see on https://github.com/gromez/allocine-api that the secret and the key changed.

But if I change them, that's not enough. However, I don't know what I have to modify... Can you help me?

link to the last commit: https://github.com/gromez/allocine-api/commit/01d7c43454d8a534a50b866dedb353b1da6b3093#diff-7f761f97cca374b2e6c626c177a2f392

**Comment by p-dor** [comment]
Thanks for your fix proposal @mic-rigaud! I was looking for it since few days...
I applied your patch on my version and unfortunately it doesn't work. Are you sure it works fine on your side?
The search is taking a long time before returning a null result...
Also your fix in the testapi.py file should rather be "from allocine import api" ;-)

**Comment by mic-rigaud** [comment]
It works for me on python3.8.2 and on python3.6.8. But it doesn't work on python3.5.3 (for this version I change the variable _userAgents_ using the traditional function _format()_ . I did it because python3.5.3 is the official version of python on rasbian, and It worked before this issue).
I think the problem is the dictionary _params_. Indeed, with this code we need a ordered dictionary which is [a language feature since python 3.7](https://stackoverflow.com/questions/39980323/are-dictionaries-ordered-in-python-3-6). So my personnal question is why my python3.6.8 ordered the variable _params_ by default?! I have done multiple test, and my variable is really ordered.
Which version of python do you use?

for the testapi.py, that depends from where do you run the script ;)

**Comment by p-dor** [comment]
Thank you for this reply. Actually I stayed with version 3.5.1 so far, did not consider upgrading as my Python app is relatively large, also using PyQT4 and other libraries, and I'm a bit scared about the time it would take to adapt...
I tried bypassing the _userAgents_ variable by using a fixed string in the _req.add_header('User-agent', 'fixed string')_ command, but unfortunately it still gives 403 errors. Could you give more details on what you mean by using the _format()_ function?
I also confirm that the _params_ dictionary is NOT ordered in my case, the order is changing at each invocation.
But... for both _User-agent_ & _params_ it was the same in my script (i.e. fixed string & not ordered params) before AlloCine changed and it worked very well, since years. Do you think more restrictions have been also introduced by this change?

**Comment by mic-rigaud** [comment]
I just made two new commits which should solve your problem and give python3.5 compatibility. :)
Can you confirm?

**Comment by p-dor** [comment]
Thank you so much @mic-rigaud it works like a charm!
I understand better now what you meant by using the standard _format()_ function...
Again thanks a lot for your help, you saved me a lot of time ;-)

**Comment by mic-rigaud** [comment]
Your welcome.
